ENH: Implement --to-dir, -l|--list, -s|--show-records
Through nanoDB, with records stored in the project's var/ subdir.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/todo-local-project b/bin/todo-local-project
--- a/bin/todo-local-project
+++ b/bin/todo-local-project
@@ -1,28 +1,67 @@
 #!/bin/bash
+set -o pipefail
 shopt -qs extglob
+${DEBUG:+eval $(debugtrace -o $- -- "$@")}
+
+readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
+[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
+readonly projectDir="${scriptDir}/.."
+readonly varDir="${projectDir}/var"
 
 printUsage()
 {
     cat <<HELPTEXT
-Synthesize an origin +project [@work] for the passed local todo.txt
+Synthesize (and record) an origin +project [@work] for the passed local todo.txt
 LOCAL-TODO-DIR / a project for the current working directory. Fails with 1 if
 the origin +project cannot be determined, and with 5 if not in a project
 directory.
 HELPTEXT
     echo
+    printf 'Usage: todo.sh -p list ... | %q %s\n' "$(basename "$1")" '--to-dir'
+    echo
+    cat <<HELPTEXT
+List all recorded origin +project [@work].
+HELPTEXT
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-l|--list'
+    echo
+    cat <<HELPTEXT
+List all origin +project [@work] and the recorded corresponding DIRs.
+HELPTEXT
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '-s|--show-records'
+    echo
     printf 'Usage: %q %s\n' "$(basename "$1")" '--to-origin [LOCAL-TODO-DIR]'
+    echo
+    cat <<HELPTEXT
+Print the corresponding recorded directory if a single recorded origin +project
+[@work] is found in the task text read from standard input. Fails with 5 if no
+or with 1 if multiple recorded origin +projects are found in the task text.
+HELPTEXT
 }
+typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
 
 action='printUsage'
 case "$1" in
     --help|-h|-\?)      shift; printUsage "$0"; exit 0;;
-    --to-origin)        shift; action='toOrigin';;
+    --to-origin)        shift; action=toOrigin; pager=();;
+    --to-dir)           shift; action=toDir; pager=();;
+    --list|-l)		shift; action=list;;
+    --show-records|-s)	shift; action=showRecords;;
     *)                  printUsage "$0" >&2; exit 2;;
 esac
+
+database()
+{
+    nanoDB --basedir "$varDir" --relaxed-key --table todo-local-project "$@"
+}
 
 printOrigin()
 {
     printf '%s\n' "$@"
+
+    IFS=' '
+    database --update "$*" --value "${localDirspec:?}"
 }
 
 toOrigin()
@@ -34,7 +73,8 @@ toOrigin()
 	*)  printUsage "$0" >&2; exit 2;;
     esac
 
-    case "${localDirspec/\/Unixhome\//\/}" in
+    localDirspec="${localDirspec/\/Unixhome\//\/}"
+    case "$localDirspec" in
 	~/@(autosource|profile))
 	    printOrigin "+rc-${localDirspec##*/}";;
 	~/lib/ingo/todo.txt-cli)
@@ -69,4 +109,39 @@ toOrigin()
     esac
 }
 
-$action "$@"
+list()
+{
+    database --query-keys \
+	| sort
+}
+
+showRecords()
+{
+    database --get-as-list $'\t' \
+	| sort \
+	| column -s $'\t' -t
+}
+
+toDir()
+{
+    typeset -a origins; readarray -t origins < <(list </dev/null)
+    if [ ${#origins[@]} -eq 0 ]; then
+	echo >&2 'ERROR: No origin +projects have been recorded in the database yet.'
+	exit 5
+    fi
+    typeset -a originGrepArgs=("${origins[@]/#/--regexp= }"); originGrepArgs=("${originGrepArgs[@]/%/ }")
+
+    typeset -a foundOrigins; readarray -t foundOrigins < <(
+	suffix ' ' \
+	    | grep --only-matching --fixed-strings "${originGrepArgs[@]}" \
+	    | sort --unique
+    )
+
+    [ ${#foundOrigins[@]} -eq 1 ] || exit 1
+    local foundOrigin="${foundOrigins[0]}"; foundOrigin="${foundOrigin# }"; foundOrigin="${foundOrigin% }"
+
+    database --query "$foundOrigin"
+}
+
+eval '$action "$@"' \
+    "${pager:+|}" '"${pager[@]}"'
