movetolocal: DWIM: ENH: Lookup DIR through TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND (zd)
This is much more convenient than having to type the entire dirspec, especially because todo.sh currently doesn't support filename completion or custom completions for add-ons.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/actions/movetolocal b/actions/movetolocal
--- a/actions/movetolocal
+++ b/actions/movetolocal
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 
+: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND='zd --selection'}
+: ${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG="QUERY|''"}
+
 export TODOTXT_MOVEELSEWHERE_SOURCE_WHAT='global / current local todo.txt file'
 export TODOTXT_MOVEELSEWHERE_DESTINATION_WHAT='local task list in DIR'
 export TODOTXT_MOVEELSEWHERE_DEFAULT_TO_ALL=0
-export TODOTXT_MOVEELSEWHERE_DEST_ARG='DIR'
+export TODOTXT_MOVEELSEWHERE_DEST_ARG="DIR${TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG:+|$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_ARG}"
 
 readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
 [ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
@@ -16,7 +19,14 @@ shift
 
 [ $# -gt 0 ] \
     || die 'TODO: Missing target directory.'
-targetDir="${1:?}"; shift
+targetDir="${1?}"; shift
+if [ ! -d "$targetDir" -a -n "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" ]; then
+    # Try to resolve the target directory through the lookup command.
+    lookedUptargetDir="$(eval "$TODOTXT_MOVETOLOCAL_DIR_LOOKUP_COMMAND" "$targetDir")"
+    [ -d "$lookedUptargetDir" ] \
+	&& targetDir="$lookedUptargetDir" \
+	|| die "TODO: Target directory does not exist, and could not look it up: $targetDir"
+fi
 [ -d "$targetDir" ] \
     || die "TODO: Target directory does not exist: $targetDir"
 targetTodoFile="${targetDir%/}/todo.txt"
